name: son_pick_and_place_wrist_image

image_shape: [3, 240, 320]
# dataset_path: /media/son/son_dataset_2/IL/dataset/rb10_pick_and_place/idp_data.hdf5

## 2TB SSD에서 읽어오니까 너무 오래걸림. 로컬에 저장해둠
dataset_path: /home/son/interactive_diffusion_policy/idp_data.hdf5

shape_meta: &shape_meta
  obs:
    image0: # wrist view
      shape: [3, 240, 320]
      type: rgb
    # image1: # global view
    #   shape: [3, 240, 320]
    #   type: rgb
    position:
      shape: [3]
      type: low_dim
    quat:
      shape: [4]
      type: low_dim
    gripper:
      shape: [1]
      type: low_dim
  action: 
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.son_replay_image_dataset.SonReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  # pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  abs_action: True
  # max_train_episodes: null
  # delta_action: False

